# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Jons Keyboard Dongle'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["jons_keyb_dongle"]'
      kconfig: '["CONFIG_BT_CTLR_TX_PWR_PLUS_8=y"]'
