# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Settings reset'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: settings_reset
